Repository Book-Study-For-Developer/Micro-State-Management-with-React-Hooks, pull requests merged in 2024-12, with the labels that each got.

#6 docs: [11/26 스터디 1회차] 1장 내용 정리
  최연수/.gitignore
  최연수/01_리액트_훅을_이용한_마이크로_상태_관리.md
Labels: 1회차, 발표자

#5 docs: [11/26 스터디 1회자] 1장 내용 정리
  장수민/01. 리액트 훅을 이용한 마이크로 상태 관리/README.md
Labels: 1회차

#8 docs: [11/26 스터디 1회차] 1장 내용 정리
  김호진/01.리액트 훅과 마이크로 상태관리/README.md
Labels: 1회차, 발표자

#4 docs: [11/26 스터디 1회차] 1장 내용 정리
  박상우/01. 리액트 훅을 이용한 마이크로 상태 관리/README.md
Labels: 1회차

#3 docs: [11/26 스터디 1회자] 1장 내용 정리
  박태준/01. 리액트 훅과 마이크로 상태관리/README.md
  박태준/01. 리액트 훅과 마이크로 상태관리/image.png
Labels: 1회차

#7 docs: [11/26 스터디 1회차] 1장 내용 정리
  고석영/01. 리액트 훅을 이용한 마이크로 상태 관리/README.md
  고석영/01. 리액트 훅을 이용한 마이크로 상태 관리/image.png
  고석영/README.md
Labels: 1회차

#9 docs: [12/03 스터디 2회차] 2,3,4장 내용 정리
  하현준/02. 지역 상태와 전역 상태 사용하기/README.md
  하현준/03. 리액트 컨텍스트를 이용한 컴포넌트 상태 공유/README.md
  하현준/04. 구독을 이용한 모듈 상태 공유/README.md
Labels: 2회차, 발표자

#16 [12/03 스터디 2회차] 2,3,4장 내용 정리
  김호진/01. 리액트 훅과 마이크로 상태관리/README.md
  김호진/02. 지역 상태와 전역 상태 사용하기/README.md
  김호진/03. 리액트 컨텍스트를 이용한 컴포넌트 상태 공유/README.md
  김호진/04. 구독을 이용한 모듈 상태 공유/README.md
Labels: 2회차

#12 docs: [12/03 스터디 2회차] 2,3,4장 내용 정리
  이재혁/2주차/02/README.md
  이재혁/2주차/03/README.md
  이재혁/2주차/03/image.png
  이재혁/2주차/04/README.md
Labels: 2회차

#15 docs: [12/03 스터디 2회차] 2,3,4장 내용 정리
  박태준/[1] Micro State Management/README.md
  박태준/[1] Micro State Management/image.png
  박태준/[2-4] Context API, Module State, Subscription/README.md
Labels: 2회차, 발표자

#13 docs: [12/03 스터디 2회차] 2,3,4장 내용 정리
  장수민/02. 전역 상태에 대한 기초적인 접근법/README.md
  장수민/03. 리액트 컨텍스트를 이용한 컴포넌트 상태 공유/README.md
  장수민/04. 구독을 이용한 모듈 상태 공유/README.md
Labels: 2회차

#14 docs: [12/03 스터디 2회차] 2,3,4장 내용 정리
  박상우/02. 지역상태와 전역 상태 사용하기/README.md
  박상우/03. 리액트 컨텍스트를 이용한 컴포넌트 상태 공유/README.md
  박상우/04. 구독을 이용한 모듈 상태 공유/README.md
Labels: 2회차, 발표자

#17 docs: [12/10 스터디 3회차] 5, 6장 내용 정리
  하현준/05. 리액트 컨텍스트와 구독을 이용한 컴포넌트 상태 공유/README.md
  하현준/06. 전역 상태 관리 라이브러리 소개/README.md
Labels: 발표자, 3회차

#24 docs: [12/10 스터디 3회차] 5, 6장 내용 정리
  김호진/05. 리액트 컨텐스트와 구독을 이용한 컴포넌트 상태 공유/README.md
  김호진/06. 전역 상태 관리 라이브러리 소개/README.md
Labels: 3회차

#18 docs: [12/10 스터디 3회차] 5, 6장 내용 정리
  이재혁/3주차/05/README.md
  이재혁/3주차/05/rerender1.png
  이재혁/3주차/05/rerender2.png
  이재혁/3주차/05/rerender3.png
  이재혁/3주차/06/README.md
Labels: 3회차

#20 docs: [12/10 스터디 3회차] 5, 6장 내용 정리
  최연수/05. 리액트 컨텍스트와 구독을 이용한 컴포넌트 상태 공유/README.md
  최연수/06. 전역 상태 관리 라이브러리 소개/README.md
Labels: 3회차

#23 docs: [12/10 스터디 3회차] 5, 6장 내용 정리
  장수민/05. 리액트 컨텍스트와 구독을 이용한 컴포넌트 상태 공유/README.md
  장수민/06. 전역 상태 관리 라이브러리 소개/README.md
Labels: 발표자, 3회차

#19 docs: [12/10 스터디 3회차] 5, 6장 내용 정리
  박태준/[5-6] Context + Subscription Pattern, State Management Library/README.md
Labels: 3회차

#22 docs: [12/10 스터디 3회차] 5, 6장 내용 정리
  박상우/05.리액트 컨택스트와 구독을 이용한 컴포넌트 상태 공유/README.md
  박상우/06.전역 상태 관리 라이브러리 소개/README.md
Labels: 발표자, 3회차

#21 docs: [12/10 스터디 3회차] 5, 6장 내용 정리
  김나영/05. 리액트 컨텍스트와 구독을 이용한 컴포넌트 상태 공유/README.md
  김나영/06. 전역 상태 관리 라이브러리 소개/README.md
Labels: 3회차

#28 docs: [12/17 스터디 4회차] 7, 8, 9장 내용 정리
  하현준/07. 사용 사례 시나리오 1: Zustand/README.md
  하현준/08. 사용 사례 시나리오 2: Jotai/README.md
  하현준/09. 사용 사례 시나리오 3: Valtio/README.md
Labels: 4회차

#35 docs: [12/17 스터디 4회차] 7, 8, 9장 내용 정리
  이재혁/4주차/07/README.md
  이재혁/4주차/08/README.md
  이재혁/4주차/09/README.md
Labels: 4회차

#30 docs: [12/17 스터디 4회차] 7, 8, 9장 내용 정리
  최연수/07. 사용 사례 시나리오 1: Zustand/README.md
  최연수/08. 사용 사례 시나리오 2: Jotai/README.md
  최연수/09. 사용 사례 시나리오 3: Valtio/README.md
Labels: 발표자, 4회차

#29 docs: [12/17 스터디 4회차] 7, 8, 9장 내용 정리
  박태준/[10-11] XState/README.md
  박태준/[10-11] XState/xstate.gif
  박태준/[7-9] Jotai/README.md
Labels: 발표자, 4회차

#33 docs: [12/17 스터디 4회차] 7, 8, 9장 내용 정리
  고석영/07. 사용 사례 시나리오 1: Zustand/README.md
  고석영/08. 사용 사례 시나리오 2: Jotai/README.md
  고석영/09. 사용 사례 시나리오 3: Valtio/README.md
  고석영/README.md
Labels: 발표자, 4회차

#34 docs: [12/17 스터디 4회차] 7, 8, 9장 내용 정리
  박상우/07.사용 사례 시나리오 1 : Zustand/README.md
  박상우/08. 사용사례 시나리오 2 : Jotai/README.md
  박상우/09 사용 사례 시나리오 3 : Valtio/README.md
Labels: 4회차

#39 docs: [12/24 스터디 5회차] 10, 11장 내용 정리
  최연수/10. 사용 사례 시나리오 4: React Tracked/README.md
  최연수/11. 세 가지 전역 상태 라이브러리의 유사점과 차이점11. 세 가지 전역 상태 라이브러리의 유사점과 차이점/README.md
Labels: 5회차

#37 docs: [12/24 스터디 5회차] 10, 11장 내용 정리
  하현준/10. 사용 사례 시나리오 4: React Tracked/README.md
  하현준/11. 세 가지 전역 상태 라이브러리 유사점과 차이점/README.md
Labels: 발표자, 5회차

#40 docs: [12/24 스터디 5회차] 10, 11장 내용 정리
  이재혁/5주차/10/README.md
  이재혁/5주차/11/README.md
Labels: 5회차
